pipeline {
    agent any
    stages {
        stage('Code') {
            steps {
                cleanWs()  
                git branch: 'main', url: 'https://github.com/Spandana115/python-flask-app.git'
            }
        }
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t app ./single-server-deployment'  
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'docker run --rm app pytest test_app.py'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'docker run -itd --name cont1 -p 5001:5000 app'
                }
            }
        }
    }
}

